disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Ignas Paškevičius"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "Ignas Paškevičius personal website"

  [params.author]
  name = "Ignas Paškevičius"
  email = "ignas[at]ignaspsk.dev"
  imageQuality = 96
  headline = "Ever-curious student and a nerd"
  bio = "Ever-curious student and a nerd"

    [[params.author.links]]
    email = "mailto:ignas@ignaspsk.dev"

    [[params.author.links]]
    github = "https://github.com/ignaspsk"
    
    [[params.author.links]]
    signal = "https://signal.me/#eu/s002U48Ts2o28Vok5Qpdy8J0Cq53UJOKyuzwQGzp_WUqtE0ygdVMuLWN1SZaEfo4"
    
    [[params.author.links]]
    mastodon = "https://mastodon.social/@ignaspsk"
    
    [[params.author.links]]
    mug-hot = "https://buymeacoffee.com/ignaspsk"
    
    [[params.author.links]]
    rss = "https://ignaspsk.dev/index.xml"
